version: '3'
services:
  redis:
    image: redis:3-alpine
    command: redis-server --appendonly no
    hostname: redis
    ports:
      - "6379:6379"



  data_redis:
    image: cogniteev/echo
    command: echo 'Data Container for Redis'
    volumes:
      - /data

  data_database:
    image: cogniteev/echo
    command: echo 'Data Container for Postgres'
    volumes:
      - /var/lib/postgresql/data
  rails:
    build: .
    command: rails s -b 0.0.0.0
    container_name: awesome_rails
    ports:
      - 3000:3000
    volumes:
      - .:/opt/app
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - awesome_rails_data:/var/lib/postgresql/data
volumes:
  awesome_rails_data:




